In [0]:
# importing necessary libraries

from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import sparse_random_matrix
import numpy as np
import timeit

In [0]:
# generate a random matrix of user ratings for music items
# users = 1 million
# music items = 5 million

n_users = 10000
n_music_items = 50000

In [0]:
X = sparse_random_matrix(n_music_items,n_users, density=0.01, random_state=45)

# **SKLEARN**

In [0]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=123)

In [0]:
#normalization and squash the  value between 0 and 1
from sklearn.preprocessing import normalize
x = np.absolute(X)
x_normalized = normalize(x, norm='l1', axis=0)

In [75]:
print x_normalized

  (234, 0)	0.0020080321285140474
  (284, 0)	0.0020080321285140474
  (554, 0)	0.0020080321285140474
  (654, 0)	0.0020080321285140474
  (655, 0)	0.0020080321285140474
  (715, 0)	0.0020080321285140474
  (718, 0)	0.0020080321285140474
  (1068, 0)	0.0020080321285140474
  (1081, 0)	0.0020080321285140474
  (1168, 0)	0.0020080321285140474
  (1178, 0)	0.0020080321285140474
  (1329, 0)	0.0020080321285140474
  (1401, 0)	0.0020080321285140474
  (1410, 0)	0.0020080321285140474
  (1418, 0)	0.0020080321285140474
  (1505, 0)	0.0020080321285140474
  (1834, 0)	0.0020080321285140474
  (1864, 0)	0.0020080321285140474
  (2001, 0)	0.0020080321285140474
  (2009, 0)	0.0020080321285140474
  (2108, 0)	0.0020080321285140474
  (2568, 0)	0.0020080321285140474
  (2597, 0)	0.0020080321285140474
  (2614, 0)	0.0020080321285140474
  (2654, 0)	0.0020080321285140474
  :	:
  (46772, 9999)	0.0021367521367521274
  (46845, 9999)	0.0021367521367521274
  (46956, 9999)	0.0021367521367521274
  (47223, 9999)	0.0021367521367521274

SVD FIT

In [0]:
start = timeit.default_timer()
x_cap = svd.fit(x_normalized)
stop = timeit.default_timer()

In [77]:
print x_cap

TruncatedSVD(algorithm='randomized', n_components=5, n_iter=7,
       random_state=123, tol=0.0)


# **speed (time taken)**

In [78]:
print stop-start

2.06390786171


# **memory utilization**

In [79]:
import sys
print sys.getsizeof(svd),sys.getsizeof(X) 

64 64


In [80]:
##printing the values of the decomposed components
print("VT")
print(svd.components_)  
print("Sigma")
print(svd.singular_values_)

VT
[[ 0.00998653  0.01002046  0.01006625 ...  0.00998956  0.00994894
   0.00997071]
 [-0.0192061  -0.00264812 -0.00685641 ... -0.03111749 -0.01327087
  -0.00676885]
 [ 0.00386587  0.01168584  0.00520264 ...  0.0148165  -0.00097988
   0.01013017]
 [ 0.00174292  0.00392516 -0.00325744 ... -0.00613744 -0.00048666
   0.00316204]
 [-0.00208161  0.00036121 -0.01118827 ... -0.00054636 -0.01055634
   0.01307337]]
Sigma
[0.44943705 0.06218267 0.06200957 0.06192296 0.06188153]


In [81]:
print(svd.explained_variance_ratio_)  

[0.00010072 0.00019496 0.00019388 0.00019333 0.00019308]


SVD FIT_TRANSFORM --  perform dimensionality reduction on X.

In [0]:
start = timeit.default_timer()
x_cap= svd.fit_transform(x_normalized)
stop = timeit.default_timer()

In [83]:
print (x_cap)

[[ 2.14363705e-03 -4.62643562e-05  2.40188422e-04  8.71246044e-05
  -6.65616052e-05]
 [ 1.97559839e-03 -3.61847282e-04 -3.05956713e-04 -2.07969644e-04
   3.39149313e-05]
 [ 1.72344960e-03  2.68323685e-04  3.24412345e-04  2.84469412e-04
  -8.57627996e-05]
 ...
 [ 1.66131144e-03 -2.11206085e-04 -7.29478667e-05  4.92674863e-04
  -1.06409480e-04]
 [ 2.04714257e-03 -2.80762465e-04 -7.12006697e-05 -2.85972745e-04
  -2.48136432e-04]
 [ 2.07534312e-03 -1.97203875e-05  3.06029994e-05 -2.40781726e-04
  -1.80981884e-04]]


In [84]:
print (stop-start)

2.12083911896


# **GENSIM**

In [59]:
!pip install gensim

In [0]:
import gensim
start = timeit.default_timer()
mat= gensim.models.lsimodel.stochastic_svd(X,2,50000)
stop = timeit.default_timer()

# **Speed (Time Taken)**

In [86]:
print stop-start

0.130005121231


# **Memory Utilization**

In [87]:
print sys.getsizeof(svd)

64


In [88]:
#sigma (singular value of corpus)
print mat[1]

[0.46252931 0.45760443]


In [89]:
#left singular value
print mat[0]

[[-0.00521031  0.01172549]
 [-0.02154479 -0.00123713]
 [-0.00842981 -0.01130095]
 ...
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]


# **Benchmark  (comparison)**

We found that in terms of time taken, the gensim method to compute SVD is almost 15 times faster than Sklearn SVD method.

However when we compared memory utilization it was almost the same.

Also the benefit of Gensim is that the whole matrix need not to be loaded into the RAM but can be operated in chunks.